version: '2.0'
services:
  # builds lambda package
  build:
    image: softprops/lambda-rust
    volumes:
    - .:/code:Z
    - ~/.cargo/registry:/root/.cargo/registry:Z
    environment:
    - BIN=lambda
